/* ???????????????????? */
function captureTurnSnapshot(action){const runtime=deepClone(state.runtime);runtime.turnSnapshot=null;runtime.activeRequestId=null;runtime.requestStartedAt=null;runtime.failedRequest=null;runtime.lastRawAiResponse=null;const data=deepClone({character:state.character,scenario:state.scenario,campaign:state.campaign,clues:state.clues,npcs:state.npcs,items:state.items,statuses:state.statuses,resources:state.resources,messages:state.messages,logs:state.logs,checkRecords:state.checkRecords,context:state.context,runtime});state.runtime.turnSnapshot={at:nowIso(),revision:state.revision,action:asString(action,4000),committed:false,requestId:null,data}}
function markTurnSnapshotCommitted(requestId){if(state.runtime.turnSnapshot&&!state.runtime.turnSnapshot.committed){state.runtime.turnSnapshot.committed=true;state.runtime.turnSnapshot.requestId=requestId||null}}
function canUndoLastTurn(){return Boolean(state.runtime.turnSnapshot?.committed)&&!activeAbortController&&!state.runtime.activeRequestId}
function undoLastTurn(){if(!canUndoLastTurn())throw new Error("没有可撤销的已完成回合");const snap=state.runtime.turnSnapshot,keep={config:deepClone(state.config),saveMeta:deepClone(state.saveMeta),ui:deepClone(state.ui),connection:state.runtime.connection,lastApiSelfCheck:deepClone(state.runtime.lastApiSelfCheck)};const restored=deepClone(snap.data);state={...makeInitialState(),...restored,config:keep.config,saveMeta:keep.saveMeta,ui:{...keep.ui,chatVisibleCount:Math.max(100,Number(keep.ui.chatVisibleCount||100))}};state.appVersion=APP_VERSION;state.schemaVersion=SCHEMA_VERSION;state.runtime={...makeInitialState().runtime,...(restored.runtime||{}),phase:"awaiting_player_action",connection:keep.connection,lastApiSelfCheck:keep.lastApiSelfCheck,turnSnapshot:null,lastUndoAt:nowIso(),activeRequestId:null,requestStartedAt:null,failedRequest:null,lastRawAiResponse:null};state.revision=Number(snap.revision||0)+1;state.messages.push({id:uid("msg"),role:"system",content:`【回合回退】已撤销行动：“${asString(snap.action,300)}”。你可以从此处修改行动并形成新的剧情分支。`,time:nowIso(),requestId:null,kind:"undo"});addLog("undo",`撤销上一轮并回到 revision ${snap.revision}`);state.runtime.isDirty=true;scheduleAutosave();renderAll();toast("已撤销上一轮","ok")}
function showUndoTurnModal(){if(!canUndoLastTurn())throw new Error("没有可撤销的已完成回合");const snap=state.runtime.turnSnapshot;openModal(`<h2>撤销上一轮</h2><div class="notice warn">将恢复到玩家提交本轮行动之前。之后产生的叙事、检定、状态变化、线索和节点推进都会撤销，并记录一次回退日志。</div><p><strong>行动：</strong>${escapeHtml(snap.action||"未记录")}</p><div class="modal-actions"><button class="btn" data-modal-close>取消</button><button id="confirmUndoTurnBtn" class="btn danger" type="button">确认撤销</button></div>`);$("#confirmUndoTurnBtn").onclick=()=>{closeModal();undoLastTurn()}}
function utf8Bytes(value){return new TextEncoder().encode(String(value??"")).length}
function formatBytes(bytes){const n=Number(bytes||0);if(n<1024)return`${n} B`;if(n<1024*1024)return`${(n/1024).toFixed(1)} KB`;return`${(n/1024/1024).toFixed(2)} MB`}
function appStorageStats(){const slots=getSaveIndex().map(item=>{const raw=APP_LOCAL_STORAGE.getItem(STORAGE_SLOT_PREFIX+item.slotId)||"";return{...item,bytes:utf8Bytes(raw)}});let total=0;for(let i=0;i<APP_LOCAL_STORAGE.length;i++){const key=APP_LOCAL_STORAGE.key(i);if(key&&key.startsWith("trpg-dm-assistant:"))total+=utf8Bytes(key)+utf8Bytes(APP_LOCAL_STORAGE.getItem(key)||"")}let currentBytes=0;try{currentBytes=utf8Bytes(JSON.stringify(serializeSave()))}catch{}return{slots,total,currentBytes}}
function clearOldAuditLogs(){const before=state.logs.length;if(before<=300){toast("当前审计日志无需清理","warn");return}state.logs=state.logs.slice(-300);bumpRevision();addLog("maintenance",`清理旧审计日志：${before} → ${state.logs.length}`);renderAll();toast("旧审计日志已清理","ok")}
function buildDiagnosticPackage({includeSecrets=false}={}){const node=getCurrentNode(),snapshot=buildContextSnapshot(state.runtime.pendingPlayerAction||"",{debug:includeSecrets});return{kind:"trpg-diagnostic",appVersion:APP_VERSION,schemaVersion:SCHEMA_VERSION,generatedAt:nowIso(),includeSecrets,config:{...deepClone(state.config),apiKey:undefined,kpDebug:undefined},runtime:{phase:state.runtime.phase,connection:state.runtime.connection,lastError:state.runtime.lastError,failedRequest:state.runtime.failedRequest?{kind:state.runtime.failedRequest.kind,stage:state.runtime.failedRequest.stage,errorCode:state.runtime.failedRequest.errorCode,errorMessage:state.runtime.failedRequest.errorMessage}:null,lastApiSelfCheck:state.runtime.lastApiSelfCheck},currentNode:node?{id:node.id,title:node.title,background:node.background}:null,navigation:deepClone(state.campaign.navigation),directorState:includeSecrets?deepClone(state.campaign.directorState):{sceneTurns:state.campaign.directorState?.sceneTurns,totalTurns:state.campaign.directorState?.totalTurns,tension:state.campaign.directorState?.tension,progress:state.campaign.directorState?.progress},messages:state.messages.filter(m=>includeSecrets||!m.secret).slice(-20),checks:state.checkRecords.filter(r=>includeSecrets||r.visibility!=="secret").slice(-10),logs:state.logs.filter(l=>includeSecrets||!l.secret).slice(-50),lastRawAiResponse:includeSecrets?state.runtime.lastRawAiResponse:null,contextMetrics:snapshot.metrics,longSessionDiagnostics:includeSecrets?snapshot.diagnostics:undefined,loreSelection:snapshot.loreSelection,storage:appStorageStats()}}
function exportDiagnosticPackage(includeSecrets=false){const doc=buildDiagnosticPackage({includeSecrets});downloadText(`trpg-diagnostic-${APP_VERSION}-${Date.now()}.json`,JSON.stringify(doc,null,2));toast("诊断包已导出","ok")}
function showDiagnosticExportModal(){openModal(`<h2>导出诊断包</h2><p>用于定位 API、检定、节点和存档问题。默认不包含主持秘密、暗骰和原始 AI 回复。</p><label class="row"><input id="includeDiagnosticSecrets" type="checkbox"><span>包含 KP 秘密、暗骰和原始 AI 响应（可能剧透）</span></label><div class="modal-actions"><button class="btn" data-modal-close>取消</button><button id="confirmDiagnosticExportBtn" class="btn primary" type="button">导出诊断包</button></div>`);$("#confirmDiagnosticExportBtn").onclick=()=>{const include=Boolean($("#includeDiagnosticSecrets").checked);closeModal();exportDiagnosticPackage(include)}}
const OUTCOME_LABELS={subject:{rescued:"目标人物已获救",dead:"目标人物已死亡",unknown:"目标人物下落未知"},truth:{full:"已掌握完整真相",partial:"仅掌握部分真相",hidden:"核心真相仍被掩盖"},evidence:{strong:"证据充分",weak:"证据有限",none:"没有可靠证据"},threat:{destroyed:"威胁已摧毁",contained:"威胁暂时受控",active:"威胁仍然活跃",spread:"威胁已经扩散"},investigator:{safe:"调查员安全",injured:"调查员受伤",broken:"调查员精神崩溃",corrupted:"调查员受到污染"}};
function outcomeSummaryHtml(outcomes){const names={subject:"人员情况",truth:"真相掌握",evidence:"证据强度",threat:"威胁状态",investigator:"调查员状态"};return`<div class="kv">${Object.keys(names).map(key=>`<span>${names[key]}</span><b>${escapeHtml(OUTCOME_LABELS[key]?.[outcomes[key]]||String(outcomes[key]||"未确定"))}</b>`).join("")}</div>`}
function loadEarlierMessages(){state.ui.chatVisibleCount=clamp(Number(state.ui.chatVisibleCount||100)+100,100,1200);renderChatLog({scrollToBottom:false,preserveOffset:true})}

function protocolSelfCheckFixtures(requestId="selfcheck",baseRevision=0){return{
  noCheck:{protocolVersion:AI_PROTOCOL_VERSION,requestId,baseRevision,decision:"no_check",narrative:"你环顾房间，没有立即发现必须检定的障碍。",check:null,stateChanges:[],campaignChanges:[],locationEffect:{type:"stay"},nodeProposal:null,endingProposal:null,actionSuggestions:[]},
  check:{protocolVersion:AI_PROTOCOL_VERSION,requestId,baseRevision,decision:"check",narrative:"你开始仔细检查现场。",check:{type:"skill",system:"coc7",skillId:"spot_hidden",label:"侦查",mandatory:false,visibility:"public",reason:"搜索异常痕迹"},stateChanges:[],campaignChanges:[],locationEffect:{type:"stay"},nodeProposal:null,endingProposal:null,actionSuggestions:[]}
}}
function validateProtocolSelfCheckLocally(){const originalCharacter=state.character;try{state.character={system:"coc7",san:60,luck:50,attributes:{str:50,con:50,siz:50,dex:50,app:50,int:50,pow:60,edu:50},skills:[{id:"spot_hidden",name:"侦查",value:55}]};const requestId="local_selfcheck",baseRevision=3,fixtures=protocolSelfCheckFixtures(requestId,baseRevision),noCheck=validateAiResponse(fixtures.noCheck,{requestId,baseRevision,stage:"action_adjudication"}),check=validateAiResponse(fixtures.check,{requestId,baseRevision,stage:"action_adjudication"}),alias=validateAiResponse({...fixtures.noCheck,campaignChanges:[{operation:"advanceClock",clockId:"clock-primary",by:1}]},{requestId,baseRevision,stage:"action_adjudication"});let rejectedUnknown=false;try{validateAiResponse({...fixtures.noCheck,stateChanges:[{operation:"unknownOperation"}]},{requestId,baseRevision,stage:"action_adjudication"})}catch{rejectedUnknown=true}return noCheck.decision==="no_check"&&check.check?.required===true&&alias.campaignChanges[0]?.amount===1&&rejectedUnknown}finally{state.character=originalCharacter}}
async function runApiProtocolSelfCheck(){
  if(activeAbortController||state.runtime.activeRequestId)throw new Error("当前已有请求正在进行");const results=[],started=nowIso();try{
    results.push({name:"本地正式校验器",ok:validateProtocolSelfCheckLocally(),detail:"执行 no_check、check.required 派生、by→amount 与未知 operation 拒绝"});
    const plain=await callChatCompletion([{role:"system",content:"只回复 OK"},{role:"user",content:"连接测试"}],{timeoutMs:Math.min(state.config.timeoutMs,20000),jsonMode:false,temperature:0.1});results.push({name:"网络、鉴权与模型",ok:/OK/i.test(plain),detail:/OK/i.test(plain)?"通过":"接口可用，但未按要求回复 OK"});
    const requestId=uid("selfcheck"),baseRevision=0,fixture=protocolSelfCheckFixtures(requestId,baseRevision).noCheck,prompt=`只返回下面结构的 JSON，不要 Markdown：${JSON.stringify(fixture)}`,raw=await callChatCompletion([{role:"system",content:"你是结构化协议测试器，只返回 JSON。"},{role:"user",content:prompt}],{timeoutMs:Math.min(state.config.timeoutMs,25000),jsonMode:true,temperature:0.1}),parsed=await parseAndRepairAiResponse(raw,{requestId,baseRevision,stage:"action_adjudication"});results.push({name:"真实 TRPG no_check 协议",ok:parsed.decision==="no_check"&&parsed.locationEffect?.type==="stay",detail:"模型响应已通过正式 validateAiResponse"});state.runtime.connection=results.every(item=>item.ok)?"ok":"failed"
  }catch(error){results.push({name:"连接或协议",ok:false,detail:redactSecrets(error.message)});state.runtime.connection="failed"}
  state.runtime.lastApiSelfCheck={at:nowIso(),started,results};const html=results.map(item=>`<div class="notice ${item.ok?"":"danger"}"><strong>${item.ok?"通过":"失败"} · ${escapeHtml(item.name)}</strong><br>${escapeHtml(item.detail)}</div>`).join("");openModal(`<h2>API 协议自检</h2>${html}<div class="modal-actions"><button class="btn" data-modal-close>关闭</button></div>`);renderTopbar();return results
}
function applyEnding(ending,reason=""){state.campaign.ending={id:ending.id,title:ending.playerTitle||ending.title,summary:ending.summary||"调查在此阶段结束。",reason:asString(reason,500),at:nowIso(),snapshot:{clues:state.clues.map(c=>c.id),flags:deepClone(state.campaign.flags),outcomes:deepClone(state.campaign.outcomes||defaultOutcomes()),hp:state.character?.hp,san:state.character?.san}};state.runtime.pendingEndingProposal=null;state.runtime.pendingNodeProposal=null;setPhase("campaign_ended",{force:true});bumpRevision();addLog("ending",`进入结局：${state.campaign.ending.title}`);addMessage("system",`【阶段结局】${state.campaign.ending.title}\n${state.campaign.ending.summary}${reason?`\n\n【触发原因】${reason}`:""}`,{kind:"ending"});renderAll()}
function confirmEndingProposal(){const p=state.runtime.pendingEndingProposal;if(!p)throw new Error("没有待确认的结局");applyEnding(p.ending,p.reason)}
function rejectEndingProposal(){const p=state.runtime.pendingEndingProposal;if(!p)return;addLog("ending",`拒绝结局提议：${p.title}`);state.runtime.pendingEndingProposal=null;setPhase("awaiting_player_action",{force:true});bumpRevision();renderAll()}
function showEndingEvaluationModal(){const endings=availableEndings(),outcomes={...defaultOutcomes(),...(state.campaign.outcomes||{})};openModal(`<h2>考虑结束调查</h2><p class="muted">未完成全部委托也可以结束。以下状态只根据玩家已确认的信息和页面真实状态评估。</p>${outcomeSummaryHtml(outcomes)}${state.config.kpDebug?`<details><summary>查看内部结局状态</summary><pre class="context-block">${escapeHtml(JSON.stringify(outcomes,null,2))}</pre></details>`:""}${endings.map(e=>`<div class="ending-option"><h3>${escapeHtml(e.playerTitle||e.title)}</h3><p>${escapeHtml(e.summary||"")}</p><button class="btn primary" data-select-ending="${escapeHtml(e.id)}">选择该结局</button></div>`).join("")||'<div class="notice">当前没有可用结局。</div>'}<div class="modal-actions"><button class="btn" data-modal-close>返回调查</button></div>`);$$('[data-select-ending]',$("#modalRoot")).forEach(button=>button.onclick=()=>{const ending=(state.scenario?.endings||[]).find(e=>e.id===button.dataset.selectEnding);if(ending){closeModal();applyEnding(ending,"玩家主动选择结束调查")}})}
function showContextViewer(){const debug=Boolean(state.config.kpDebug),snapshot=buildContextSnapshot(state.runtime.pendingPlayerAction||"",{debug}),envelope=state.runtime.lastContextEnvelope;const section=(title,value)=>`<h3>${escapeHtml(title)} <span class="muted">${countChars(value)} 字符</span></h3><pre class="context-block">${escapeHtml(typeof value==="string"?value:JSON.stringify(value,null,2))}</pre>`;openModal(`<h2>本轮发送内容查看器</h2><div class="notice ${debug?"warn":""}">${debug?"KP 调试模式已开启：将显示主持情境、暗骰和完整请求。":"普通模式隐藏主持秘密和暗骰。每层显示估算字符数。"}</div><div class="kv"><span>估算总字符</span><b>${snapshot.metrics.total}</b><span>预算</span><b>${snapshot.metrics.budget}</b><span>触发资料卡</span><b>${snapshot.loreSelection.length}</b></div>${section("系统规则",snapshot.systemRules)}${section("角色与核心状态",snapshot.trueState)}${section("当前场景",snapshot.currentScene)}${section("NPC 连续性",snapshot.npcContinuity)}${debug?section("世界连续性",snapshot.worldContinuity):""}${debug?section("长团诊断",snapshot.diagnostics||{}):""}${section("永久事实",snapshot.pinnedFacts)}${section("调查方向",snapshot.activeLeads)}${section("未解决问题",snapshot.unresolvedQuestions)}${section("导演注记",snapshot.directorNote)}${section("已触发资料卡",snapshot.activeLoreCards)}${section("资料卡触发原因",snapshot.loreSelection)}${section("滚动摘要",snapshot.rollingSummary||"尚无摘要")}${section(`最近消息（${snapshot.recentMessages.length} 条）`,snapshot.recentMessages)}${section("最近检定",snapshot.recentChecks)}${section("本次玩家行动",snapshot.playerAction||"尚未输入")}${section("节奏指令",snapshot.pacingDirective)}${debug?section("主持情境",snapshot.scenarioDirector):""}${debug?section("暗骰记录",snapshot.secretChecks):""}${debug&&envelope?section("最近一次完整 API Envelope",envelope):""}<div class="modal-actions"><button class="btn" data-modal-close>关闭</button></div>`)}
function showImprovSetupModal(){if(!state.character){toast("请先创建角色，再生成与角色身份匹配的即兴开场。","warn",5000);showView("character");return}openModal(`<h2>生成即兴调查开场</h2><form id="improvSetupForm"><div class="grid three"><div class="field"><label>年代</label><select name="era"><option>1920 年代</option><option>现代</option><option>近未来</option></select></div><div class="field"><label>题材</label><select name="theme"><option>随机</option><option>都市调查</option><option>乡村怪谈</option><option>封闭空间</option><option>失踪事件</option><option>神秘遗物</option><option>医疗恐怖</option><option>海洋恐怖</option><option>宗教与民俗</option></select></div><div class="field"><label>预计时长</label><select name="length"><option>短篇，约 30～60 分钟</option><option selected>标准，约 1～2 小时</option><option>较长，约 2～4 小时</option></select></div></div><div class="grid"><div class="field"><label>地区或环境</label><input name="location" placeholder="例如：江南小城、沿海港口、山间列车"></div><div class="field"><label>恐怖程度</label><select name="horror"><option>低</option><option selected>中</option><option>高</option></select></div><div class="field"><label>战斗比例</label><select name="combat"><option selected>低</option><option>中</option><option>高</option></select></div><div class="field"><label>玩家身份补充</label><input name="identity" value="${escapeHtml(state.character.occupation||state.character.className||"调查员")}"></div></div><div class="grid"><div class="field"><label>希望出现的元素</label><textarea name="include" placeholder="可留空"></textarea></div><div class="field"><label>不希望出现的元素</label><textarea name="exclude" placeholder="可留空"></textarea></div></div><div class="modal-actions"><button class="btn" type="button" data-modal-close>取消</button><button id="cancelImprovGenerationBtn" class="btn danger hidden" type="button">取消生成</button><button id="generateImprovBtn" class="btn primary" type="submit">生成开场档案</button></div></form>`);const form=$("#improvSetupForm");$("#cancelImprovGenerationBtn").onclick=cancelImprovGeneration;form.onsubmit=e=>{e.preventDefault();const prefs=Object.fromEntries(new FormData(form).entries());generateImprovOpening(prefs).catch(error=>toast(redactSecrets(error.message),"danger",7000))}}
